services:
  - type: web
    name: box-packing-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: BASE_URL
        sync: false
